eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          default-label: master
          try-master-branch: true
          uri: https://github.com/pblgllgs/sb3-mcsvcs-product-order-payment-config-files
server:
  port: 8888
